# AutoGen BIRD SQL Multi-Agent System Configuration

# General settings
max_iterations: 3  # Maximum number of refinement iterations

# Selector Agent configuration
selector:
  model: "gpt-4"  # Can be replaced with any compatible model
  temperature: 0.2
  config_list:
    - model: "gpt-4"
      api_key: "${OPENAI_API_KEY}"  # Will be replaced with actual API key from environment

# Decomposer Agent configuration
decomposer:
  model: "gpt-4"
  temperature: 0.2
  config_list:
    - model: "gpt-4"
      api_key: "${OPENAI_API_KEY}"

# Refiner Agent configuration
refiner:
  model: "gpt-4"
  temperature: 0.2
  config_list:
    - model: "gpt-4"
      api_key: "${OPENAI_API_KEY}"

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/output.log"